---
name: actionlint
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: get_actionlint
        run: |
          curl -sSfL https://github.com/rhysd/actionlint/releases/latest/download/actionlint_linux_amd64.zip -o actionlint.zip
          unzip actionlint.zip
          sudo mv actionlint /usr/local/bin
        shell: bash
      - name: Check workflow files
        run: actionlint
        shell: bash

  