---
name: actionlint
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: get_actionlint
        run: |
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | sh -s --
          sudo mv bin/actionlint /usr/local/bin/actionlint
        shell: bash
      - name: Check workflow files
        run: actionlint
        shell: bash

  