# SPDX-FileCopyrightText: Copyright (c) 2023-2025 Yegor Bugayenko
# SPDX-FileCopyrightText: Copyright (c) 2025 owtotwo
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: docs
'on':
  push:
  pull_request:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cargo test --doc --all-features -- --nocapture
      - run: cargo doc --all-features --no-deps
        env:
          RUSTDOCFLAGS: '--cfg docsrs'
